save_dir: dense_baseline_fkeras_test

model:
  name: fkeras_dense_model
  input_shape: 13
  dense_width: 58
  logit_total_bits: 4
  logit_int_bits: 0
  activation_total_bits: 8
  activation_int_bits: 0